# Generated by Django 4.2.7 on 2023-11-21 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_member_bank_account_member_bank_name_member_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='bank_account',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
