# Generated by Django 4.2.7 on 2023-11-21 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_alter_member_bank_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='monthly_contribution',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
