# Generated by Django 4.2.7 on 2023-11-21 18:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('managements', '0002_portfolio_executive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='executive',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='executives', to=settings.AUTH_USER_MODEL),
        ),
    ]
