# Generated by Django 4.2.7 on 2023-11-20 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0003_rename_amount_paid_loanrepayment_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='is_disbursed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='loan',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
