# Generated by Django 4.2.7 on 2023-11-21 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0006_alter_loan_member'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loan',
            old_name='amount',
            new_name='borrowed_amount',
        ),
        migrations.RenameField(
            model_name='loan',
            old_name='repayment_balance',
            new_name='repaid_amount',
        ),
    ]
