# Generated by Django 4.2.7 on 2023-11-28 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0010_fooditem_vendorhomeappliances_homeappliance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vendorhomeappliances',
            name='phone',
            field=models.CharField(max_length=11),
        ),
    ]
